### ISSUE TITLE
Change Fonts

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#1]
Jake: "Regarding Elizabeths note on the fonts. Lets do this. Make all Navigation and headline fonts be Huntress which i will send to you and all body text will be in the suggested font that Elizabeth sent through. Now there were two fonts she showed "Headline" and "Products" were in two different fonts. We would like to use the front that "Products" is in."

Jake, can you provide font? Also, I am not sure what you meant about "Headline" vs "Products" ... can you please clarify and/or provide links? Thanks.

**Comment by departmentofgood** [comment]
as we spoke about on the phone today, let's change the fonts only if it is easy and not time consuming for now
