### ISSUE TITLE
Marquee Highlight Boxes Sizing

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#10]
Make square highlight images smaller (4 across) and allow everything under them to move up on page. (we like the size of the rectangle highlights.) This can roughly match the mock up i sent through. The sizing of the highlight boxes needs to be adjusted.

**Comment by departmentofgood** [comment]
let's not focus on that now, the sizing is ok for the time being.

**Comment by UncommonUnion** [comment]
This was relatively quick, so I added support for this. However, I did not make use of it in the storefronts. That is, the system will size the highlights in 3 or 4 columns automatically depending how many are assigned. If there are > 3, 4 column spacing will be used.
