### ISSUE TITLE
Storefront Design

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#15]
Jake: "Departments Home Page - should look like main DOG home page with sliders showing the different products the platform sells with the highlight boxes highlighting products and the brands on our platform."

The designs are based on mocked up... can you be more specific about any necessary changes?

**Comment by departmentofgood** [comment]
As an example, when I click on Departments, the marquee can show one slider that highlights clothing, one that highlights a charity and one that highlights music or any other potential department category we will have. For the alpha we can make it somewhat fictitious.  But the point is to highlight the different departments on our platform.

**Comment by UncommonUnion** [comment]
There is not an asset for every category and to make them all will be a big task. I set up default assignments so if no sliders or highlight is assigned to a category, it will show default assignments.
