### ISSUE TITLE
About Us Link

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#2]
Jake: "For the About Us drop down, can we please remove all of the sub navigation and only have one click through as of now that reads 'Our Purpose' "

Jake are you saying I should replace About Us with Our Purpose ...?

**Comment by departmentofgood** [comment]
Yes, let's hide "About Us" and add "Our Purpose" I gave notes and attachments on this on another note so let me know if you need help finding.

**Comment by UncommonUnion** [comment]
This is a redundant ticket. Closing.
