### ISSUE TITLE
Add Collection Support to Products Highlight, Confirm Storefront Links are Finalized

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#3]
Jake: "And just to reinforce the last email i sent, we want to make sure that when clicking on each tab it takes us to the respective click through page. Example (Stripes advertisement should go to a page of all striped products). Mens click through should only have mens products, no womens and so on and so on."

Jake: "Those square highlights are there to highlight any product/collection/brand partner/ cause we wish. Should be able to be flexible on what we highlight in all highlight boxes both square and rectangle. "

**Comment by departmentofgood** [comment]
Making sure every clickable tab, highlight or button takes you to the appropriate page.
