### ISSUE TITLE
About Us / Our Purpose Navigation Link

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#4]
Should link to charity page (same page.)

**Comment by departmentofgood** [comment]
as we spoke about, lets hide the "about us" tab and replace it temporarily with "OUR PURPOSE" and it should click through to it's own page like the attached mock up. Here is the image file for that page as well. 
<img width="1745" alt="screen shot 2016-05-11 at 11 39 17 am" src="https://cloud.githubusercontent.com/assets/19331591/15225677/4080ece6-1834-11e6-99df-52124cbd27c1.png">
[Web Assests copy.pdf](https://github.com/DeptofGood/site/files/262017/Web.Assests.copy.pdf)

**Comment by UncommonUnion** [comment]
added
