### ISSUE TITLE
Add Charity Assignments for Demo Product

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#5]
On each individual product page we need the bullet points that says which cause the product is attached to and the impact it is having.

**Comment by departmentofgood** [comment]
please implement the mock up text copy attached here. 
[Charity:Impact information for products and charity drop down..docx](https://github.com/DeptofGood/site/files/262013/Charity.Impact.information.for.products.and.charity.drop.down.docx)

**Comment by UncommonUnion** [comment]
done
