### ISSUE TITLE
Multiple Button Support for Slides

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#6]
Jake: "The multiple buttons are for the consumer to have choice of shopping or learning but we do not need to have them, i will review with the team this morning and let you know."

**Comment by departmentofgood** [comment]
we do not need multiple buttons. keep it simple with either "shop now" or "learn more"

**Comment by UncommonUnion** [comment]
This feature was added with button support. You can, of course, only use one button.
