### ISSUE TITLE
Left Column Navigation

### ISSUE THREAD

**Issue by UncommonUnion** [DeptofGood/site#8]
Jake: "Place sub navigation on let hand side of screen on all ecom pages for more detailed search criteria."

Jake, I am not sure what "all ecom pages" are? It is already on all product pages and storefronts - what other pages should I add it?

**Comment by departmentofgood** [comment]
What is your opinion. I think we should allow the consumer to drill down their search criteria using the side bar navication check boxes on all shopping pages. (So potentially the whole site.) but for now just on each page that has the product thumbnails. So if i am shopping mens tees, that side navigation is always there to help me find colors, sizes and categories .

**Comment by UncommonUnion** [comment]
It already works like this... it is on every browser and product page, so I don't know where else to add it to. I am closing this unless there is a specific URL you can provide as an example where is should be added?
